# This is a basic workflow to automatically build and test at each commit to git repo.

name: Android Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2
      # Setup JDK
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      # Grant execute permission for gradlew
      - name: Grant Permission
        run: chmod +x gradlew
      # Assemble and Test Project
      - name: Build Project
        run: ./gradlew build

  androidUiTest:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      # Grant execute permission for gradlew
      - name: Grant Permission
        run: chmod +x gradlew
      # Run UI Tests
      - name: Run UI Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 25
          target: default
          arch: x86
          profile: Galaxy Nexus
          disable-animations: true
          script: ./gradlew connectedCheck --stacktrace

  apiTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Run the POSTMAN Collection
      - name: Run POSTMAN Collection
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: ./postman/MusicNow-collection.json
          reporters: cli
      # Printout the Summary in Console
      - name: Output Details
        run: echo ${{ steps.run-newman.outputs.summary }}